[package]
name = "sigscan"
description = "Search for a pattern in a file, outputting the offset in hexadecimal or 'none' if not found"
version = "0.1.2"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }

[profile.release]
panic = "abort"
strip = true
lto = true
